In [25]:
import pandas as pd
from pathlib import Path
from sklearn.cluster import KMeans

In [26]:
data_dir = Path("data")
INDIR = Path("data/data_processed")
OUTDIR = Path("data/data_model")

OUTDIR.mkdir(parents=True, exist_ok=True)

In [27]:
arquivo_df = INDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_BRASIL_TRATADO.csv"
arquivo_scaled = INDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_BRASIL_MODELO.csv"

df_clustering = pd.read_csv(arquivo_df, encoding='utf-8')
X_scaled = pd.read_csv(arquivo_scaled, encoding='utf-8')

In [28]:
kmeans = KMeans(n_clusters=3, n_init=200, random_state=0)
kmeans.fit(X_scaled)

labels = kmeans.labels_
df_clustering['CLUSTER'] = labels

In [29]:
caminho_cluster = OUTDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_BRASIL_CLUSTERS_3.csv"
df_clustering.to_csv(caminho_cluster, index=False)

In [30]:
centroids = pd.DataFrame(
    kmeans.cluster_centers_,
    columns=X_scaled.columns
)

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

display(centroids.round(2))

,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA
0,-0.16,-0.08,-0.06,-0.12,0.07
1,-1.18,-1.25,-1.26,-1.21,-1.11
2,1.20,1.15,1.13,1.17,0.83

In [31]:
df_clustering.head()

,NO_MUNICIPIO_PROVA,UF,QTD_PARTICIPANTES,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA,CLUSTER
0,ABAETETUBA,PA,4380,464.503151,473.275868,492.725731,476.596621,636.082192,1.153964,1
1,ABAETÉ,MG,529,492.048204,523.686200,539.515501,547.043478,680.982987,2.077922,2
2,ABREU E LIMA,PE,1687,475.696799,499.807232,518.264790,497.287730,625.714286,1.296622,0
3,ACARAPE,CE,374,467.339037,487.118449,507.952406,506.521390,671.497326,1.005342,0
4,ACARAÚ,CE,1013,478.360711,489.732379,510.916486,530.821718,757.255676,1.122531,0

In [32]:
resumo_clusters = (
    df_clustering
    .groupby("CLUSTER")
    .agg(
        QTD_MUNICIPIOS=("NO_MUNICIPIO_PROVA", "count"),
        NU_NOTA_CN_MEDIA=("NU_NOTA_CN_MEDIA", "mean"),
        NU_NOTA_CH_MEDIA=("NU_NOTA_CH_MEDIA", "mean"),
        NU_NOTA_LC_MEDIA=("NU_NOTA_LC_MEDIA", "mean"),
        NU_NOTA_MT_MEDIA=("NU_NOTA_MT_MEDIA", "mean"),
        NU_NOTA_REDACAO_MEDIA=("NU_NOTA_REDACAO_MEDIA", "mean"),
        RENDA_FAMILIAR_SM_MEDIA=("RENDA_FAMILIAR_SM_MEDIA", "mean"),
    )
    .reset_index()
    .sort_values("CLUSTER")
    .reset_index(drop=True)
)



resumo_clusters.columns = [col.upper() for col in resumo_clusters.columns]
display(resumo_clusters.round(2))

,CLUSTER,QTD_MUNICIPIOS,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA
0,0,740,478.30,499.82,517.61,507.47,649.10,1.54
1,1,444,455.10,467.67,491.51,470.66,602.66,1.14
2,2,533,509.28,533.62,543.63,550.71,678.53,2.27