In [49]:
import pandas as pd
from pathlib import Path
from sklearn.cluster import KMeans

In [50]:
data_dir = Path("data")
INDIR = Path("data/data_processed")
OUTDIR = Path("data/data_model")

OUTDIR.mkdir(parents=True, exist_ok=True)

In [51]:
arquivo_df = INDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_SP_TRATADO.csv"
arquivo_scaled = INDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_SP_MODELO.csv"

df_clustering = pd.read_csv(arquivo_df, encoding='utf-8')
X_scaled = pd.read_csv(arquivo_scaled, encoding='utf-8')

In [52]:
kmeans = KMeans(n_clusters=3, n_init=1000, random_state=0)
kmeans.fit(X_scaled)

labels = kmeans.labels_
df_clustering['CLUSTER'] = labels

In [53]:
caminho_cluster = OUTDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_SP_CLUSTERS.csv"
df_clustering.to_csv(caminho_cluster, index=False)

In [54]:
centroids = pd.DataFrame(
    kmeans.cluster_centers_,
    columns=X_scaled.columns
)

pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

display(centroids.round(2))

,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_LOG_MEDIANA,REGIAO_CAPITAL,REGIAO_INTERIOR,REGIAO_LITORAL
0,-1.40,-1.34,-1.23,-1.44,-1.37,-1.22,-0.00,0.80,0.20
1,-0.18,-0.21,-0.23,-0.13,-0.01,-0.16,0.00,0.95,0.05
2,0.96,0.96,0.93,0.93,0.76,0.84,0.01,0.97,0.01

In [55]:
df_clustering.head()

,NO_MUNICIPIO_PROVA,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA,REGIAO,CLUSTER
0,ADAMANTINA,525.810123,554.820000,557.684444,583.616296,695.506173,2.752041,INTERIOR,2
1,AGUDOS,520.218269,540.266346,551.470513,568.333333,689.871795,2.883191,INTERIOR,2
2,AMERICANA,533.845202,558.039175,560.798216,590.087470,704.480571,3.621081,INTERIOR,2
3,AMPARO,531.318845,552.114015,559.059280,588.289583,686.837121,2.927684,INTERIOR,2
4,ANDRADINA,502.544260,524.655960,541.908609,549.461258,665.651214,2.593284,INTERIOR,1

In [56]:
def moda_ou_na(serie):
    moda = serie.mode()
    return moda.iat[0] if not moda.empty else pd.NA

def top2_ou_na(serie):
    if serie.empty:
        return pd.NA
    return " / ".join(serie.value_counts().head(2).index.astype(str))

resumo_clusters = (
    df_clustering
    .groupby("CLUSTER")
    .agg(
        NU_NOTA_CN_MEDIA=("NU_NOTA_CN_MEDIA", "mean"),
        NU_NOTA_CH_MEDIA=("NU_NOTA_CH_MEDIA", "mean"),
        NU_NOTA_LC_MEDIA=("NU_NOTA_LC_MEDIA", "mean"),
        NU_NOTA_MT_MEDIA=("NU_NOTA_MT_MEDIA", "mean"),
        NU_NOTA_REDACAO_MEDIA=("NU_NOTA_REDACAO_MEDIA", "mean"),
        RENDA_FAMILIAR_SM_MEDIA=("RENDA_FAMILIAR_SM_MEDIA", "mean"),
    )
    .reset_index()
    .sort_values("CLUSTER")
    .reset_index(drop=True)
)



resumo_clusters.columns = [col.upper() for col in resumo_clusters.columns]
display(resumo_clusters.round(2))

,CLUSTER,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA
0,0,489.86,520.02,538.62,522.28,629.95,2.14
1,1,508.02,534.41,546.96,551.74,668.91,2.61
2,2,524.93,549.32,556.71,575.61,691.04,3.04