In [ ]:
import pandas as pd
from pathlib import Path
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import StandardScaler

In [20]:
data_dir = Path("data")
INDIR = Path("data/data_raw")
OUTDIR = Path("data/data_processed")

OUTDIR.mkdir(parents=True, exist_ok=True)

In [21]:
arquivo = INDIR / "PARTICIPANTES_2024.csv"
df = pd.read_csv(arquivo, sep=';', encoding='latin-1')

In [22]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

display(df.head(10))

,NU_INSCRICAO,NU_ANO,TP_FAIXA_ETARIA,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ENSINO,IN_TREINEIRO,CO_MUNICIPIO_PROVA,NO_MUNICIPIO_PROVA,CO_UF_PROVA,SG_UF_PROVA,Q001,Q002,Q003,Q004,Q005,Q006,Q007,Q008,Q009,Q010,Q011,Q012,Q013,Q014,Q015,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023
0,210062064233,2024,5,F,1,1,1,1,3,NaN,0,4314902,Porto Alegre,43,RS,F,F,C,D,4,B,C,A,C,D,C,B,B,A,B,B,B,D,A,B,B,E,A
1,210062064234,2024,11,F,1,1,1,1,10,NaN,0,4318903,São Luiz Gonzaga,43,RS,B,C,A,D,2,B,E,A,B,B,B,B,B,A,A,A,A,B,A,B,A,C,A
2,210062064235,2024,11,F,1,1,1,1,9,NaN,0,4320107,Sarandi,43,RS,H,F,F,D,5,B,J,A,C,D,B,B,C,A,B,B,B,D,B,B,A,D,A
3,210062064236,2024,3,F,1,3,1,2,0,1.0,0,4313409,Novo Hamburgo,43,RS,B,B,B,B,6,A,C,A,B,C,B,A,B,A,B,A,A,A,A,B,A,D,A
4,210062064237,2024,16,M,3,1,1,1,18,NaN,0,4309209,Gravataí,43,RS,B,B,C,C,2,A,A,A,B,C,A,A,B,A,A,A,A,B,A,B,A,B,A
5,210062064266,2024,12,M,2,1,1,1,3,NaN,0,4300604,Alvorada,43,RS,C,C,A,B,2,A,B,A,B,B,A,A,B,A,B,B,A,B,A,B,A,B,B
6,210062064267,2024,1,M,1,1,1,3,0,NaN,1,4307005,Erechim,43,RS,G,F,E,D,3,A,D,A,B,C,B,A,B,A,B,B,A,B,B,B,B,D,D
7,210062064268,2024,15,F,2,3,1,4,0,NaN,0,4312401,Montenegro,43,RS,B,B,F,F,2,B,C,A,B,B,B,A,B,A,B,B,A,A,A,B,A,B,F
8,210062064307,2024,16,M,3,1,1,1,18,NaN,0,4304606,Canoas,43,RS,B,C,B,C,1,B,C,A,B,B,B,A,B,A,A,B,A,B,A,A,B,B,B
9,210062064308,2024,11,F,1,3,1,1,10,NaN,0,4316907,Santa Maria,43,RS,E,B,C,B,2,A,E,A,B,D,A,A,B,A,B,B,B,B,B,B,B,C,A

In [23]:
df_simplificado = df[['TP_FAIXA_ETARIA', 'TP_SEXO', 'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'IN_TREINEIRO', 'SG_UF_PROVA', 'Q007']]

In [24]:
df_simplificado.isnull().mean()*100

TP_FAIXA_ETARIA    0.0
TP_SEXO            0.0
TP_ESTADO_CIVIL    0.0
TP_COR_RACA        0.0
IN_TREINEIRO       0.0
SG_UF_PROVA        0.0
Q007               0.0
dtype: float64

In [25]:
df_simplificado.info()

<class 'pandas.DataFrame'>
RangeIndex: 4332944 entries, 0 to 4332943
Data columns (total 7 columns):
 #   Column           Dtype
---  ------           -----
 0   TP_FAIXA_ETARIA  int64
 1   TP_SEXO          str
 2   TP_ESTADO_CIVIL  int64
 3   TP_COR_RACA      int64
 4   IN_TREINEIRO     int64
 5   SG_UF_PROVA      str
 6   Q007             str
dtypes: int64(4), str(3)
memory usage: 231.4 MB

In [26]:
df_simplificado['TP_SEXO'].value_counts()

TP_SEXO
F    2624621
M    1708323
Name: count, dtype: int64

In [27]:
faixa_etaria_map = {
    1: 16,
    2: 17,
    3: 18,
    4: 19,
    5: 20,
    6: 21,
    7: 22,
    8: 23,
    9: 24,
    10: 25,
    11: (26+30)/2,
    12: (31+35)/2,
    13: (36+40)/2,
    14: (41+45)/2,
    15: (46+50)/2,
    16: (51+55)/2,
    17: (56+60)/2,
    18: (60+80)/2,
    19: (60+80)/2,
    20: (60+80)/2
}


df_simplificado = df_simplificado.rename(columns={'TP_FAIXA_ETARIA': 'IDADE'})
df_simplificado['IDADE'] = df_simplificado['IDADE'].map(faixa_etaria_map)
df_simplificado['IDADE'] = df_simplificado['IDADE'].astype('int64')

In [28]:
cor_raca_map = {
    0: "NÃO DECLARADO",
    1: "BRANCA",
    2: "PRETA",
    3: "PARDA",
    4: "AMARELA",
    5: "INDÍGENA",
    # 6: "NÃO DISPÕE DA INFORMAÇÃO" -> AGRUPADO COM 0 POR SIMPLIFICAÇÃO
    6: "NÃO DECLARADO"
}

df_simplificado['TP_COR_RACA'] = df_simplificado['TP_COR_RACA'].map(cor_raca_map)
df_simplificado = df_simplificado[df_simplificado['TP_COR_RACA'] != 'NÃO DECLARADO']

In [29]:
df_simplificado = df_simplificado[df_simplificado['IN_TREINEIRO'] != 1]
df_simplificado = df_simplificado.drop(columns=['IN_TREINEIRO'])

In [30]:
cor_renda_map = {
    "A": 0,
    "B": 1412/2,
    "C": (1412+2118)/2,
    "D": (2118+2824)/2,
    "E": (2824+3530)/2,
    "F": (3530+4236)/2,
    "G": (4236+5648)/2,
    "H": (5648+7060)/2,
    "I": (7060+8472)/2,
    "J": (8472+9884)/2,
    "K": (9884+11296)/2,
    "L": (11296+12708)/2,
    "M": (12708+14120)/2,
    "N": (14120+16944)/2,
    "O": (16944+21180)/2,
    "P": (21180+28240)/2,
    "Q": (28240+35000)/2
}

df_simplificado['Q007'] = df_simplificado['Q007'].map(cor_renda_map)
df_simplificado['Q007'] = df_simplificado['Q007'].astype("Float64")
df_simplificado = df_simplificado.rename(columns={'Q007': 'RENDA_FAMILIAR'})

In [31]:
estado_civil_map = {
    0: "NAO_INFORMADO",
    1: "SOLTEIRO",
    2: "UNIAO",
    3: "DIVORCIADO",
    4: "NAO_INFORMADO" # Simplificando
}

df_simplificado['TP_ESTADO_CIVIL'] = df_simplificado['TP_ESTADO_CIVIL'].map(estado_civil_map)
df_simplificado = df_simplificado[df_simplificado['TP_ESTADO_CIVIL'] != 'NAO_INFORMADO']

In [32]:
caminho_tratado = OUTDIR / "PARTICIPANTES_SIMPLIFICADO_TRATADO.csv"
df_simplificado.to_csv(caminho_tratado, index=False)

In [33]:
df_simplificado.head()

   IDADE TP_SEXO TP_ESTADO_CIVIL TP_COR_RACA SG_UF_PROVA  RENDA_FAMILIAR
0     20       F        SOLTEIRO      BRANCA          RS          1765.0
1     28       F        SOLTEIRO      BRANCA          RS          3177.0
2     28       F        SOLTEIRO      BRANCA          RS          9178.0
3     18       F        SOLTEIRO       PARDA          RS          1765.0
4     53       M      DIVORCIADO      BRANCA          RS             0.0

In [34]:
df_modelagem = pd.get_dummies(
    df_simplificado,
    columns=['TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_SEXO']
)

In [35]:
scaler = StandardScaler()
df_modelagem[['RENDA_FAMILIAR', 'IDADE']] = scaler.fit_transform(df_modelagem[['RENDA_FAMILIAR', 'IDADE']])

In [36]:
caminho_modelo = OUTDIR / "PARTICIPANTES_SIMPLIFICADO_TRATADO_MODELO.csv"
df_modelagem.to_csv(caminho_modelo, index=False)

In [37]:
df_modelagem.head()

,IDADE,SG_UF_PROVA,RENDA_FAMILIAR,TP_ESTADO_CIVIL_DIVORCIADO,TP_ESTADO_CIVIL_SOLTEIRO,TP_ESTADO_CIVIL_UNIAO,TP_COR_RACA_AMARELA,TP_COR_RACA_BRANCA,TP_COR_RACA_INDÍGENA,TP_COR_RACA_PARDA,TP_COR_RACA_PRETA,TP_SEXO_F,TP_SEXO_M
0,-0.255098,RS,-0.271295,False,True,False,False,True,False,False,False,True,False
1,0.792775,RS,0.035259,False,True,False,False,True,False,False,False,True,False
2,0.792775,RS,1.338111,False,True,False,False,True,False,False,False,True,False
3,-0.517066,RS,-0.271295,False,True,False,False,False,False,True,False,True,False
4,4.067377,RS,-0.654487,True,False,False,False,True,False,False,False,False,True