In [177]:
import pandas as pd
from pathlib import Path
import plotly.express as px

In [178]:
data_dir = Path("data")
INDIR = Path("../data/data_model")

In [182]:
df = pd.read_csv(INDIR / "ANALISE_NOTAS_ENEM_MUNICIPIOS_BRASIL_CLUSTERS_2024.csv", sep=",")

In [183]:
df.head()

,NO_MUNICIPIO_PROVA,UF,QTD_PARTICIPANTES,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA,CLUSTER
0,ABAETETUBA,PA,4890,461.314479,466.065501,483.305317,473.035583,586.355828,1.253781,0
1,ABAETÉ,MG,546,492.137179,523.886996,539.278022,547.032601,667.326007,2.451439,2
2,ABREU E LIMA,PE,1810,473.122486,493.848674,513.249448,493.806796,589.690608,1.359065,1
3,ACARAPE,CE,410,464.850244,480.734878,500.530488,501.268537,622.585366,1.005342,1
4,ACARAÚ,CE,1141,473.460035,479.478002,499.146012,521.760649,683.032428,1.161161,1

In [187]:
df_cluster_2 = df[df["CLUSTER"] == 2]
df_cluster_2 = df_cluster_2.sort_values(by="RENDA_FAMILIAR_SM_MEDIA", ascending=True)
df_cluster_2.head(10)

,NO_MUNICIPIO_PROVA,UF,QTD_PARTICIPANTES,NU_NOTA_CN_MEDIA,NU_NOTA_CH_MEDIA,NU_NOTA_LC_MEDIA,NU_NOTA_MT_MEDIA,NU_NOTA_REDACAO_MEDIA,RENDA_FAMILIAR_SM_MEDIA,CLUSTER
1575,TAVARES,PB,440,478.543409,509.367955,523.642273,543.402955,659.000000,1.147126,2
477,CRUZ,CE,444,488.088514,508.054730,518.277252,552.251577,676.936937,1.332425,2
1337,RUSSAS,CE,1165,492.106524,516.177082,524.132532,546.014592,630.060086,1.468041,2
697,IRECÊ,BA,2285,490.374267,514.096193,524.266083,523.830372,648.805252,1.611475,2
870,LIMOEIRO DO NORTE,CE,1810,497.044862,514.498729,524.151878,541.825856,668.751381,1.633204,2
163,BARBALHA,CE,1683,494.139869,509.217112,520.617528,533.786275,653.226381,1.636434,2
347,CAPELINHA,MG,931,485.256928,514.571214,524.503222,527.416004,661.546724,1.719441,2
473,CRATO,CE,3170,494.027666,515.534984,527.154890,532.075868,663.141956,1.729233,2
962,MIMOSO DO SUL,ES,384,495.646875,508.586198,527.729688,521.076823,691.875000,1.752941,2
533,ERVÁLIA,MG,349,497.609742,532.186533,535.775645,539.721203,660.744986,1.762315,2